#!/bin/bash
# ref to https://stackoverflow.com/questions/7470165/how-to-go-to-each-directory-and-execute-a-command
# go into every subfolder and execute command, not include current folder
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [command]"
    exit 1
}

command=${@}

if [ -z "${command}" ]; then
    usage
fi

#find . -maxdepth 1 -type d \( ! -name . \) -exec bash -c "cd '{}' && pwd" \;

find . -maxdepth 1 -type d \( ! -name . \) -exec bash -c "cd '{}' && pwd && ${command}" \;
