#!/bin/bash
#find . -type f -name .git -prune -o -print | xargs grep "${1}"
#find . -type f | xargs grep "${1}" | grep -v ".git"
find . -type f -not -path '*/\.git/*' -print0 | xargs -0 grep -F "${1}"
