#!/bin/bash
ME=$(basename $0)

function usage() {
    echo "Usage: ${ME} [mac_address] [subnet]"
    echo "Example:"
    echo "  ${ME} 11:22:33:44:55:66 10.0.15.0/24"
    exit 1
}

macstr=${1}
subnet=${2}

if [ -z "${macstr}" ] || [ -z "${subnet}" ]; then
    usage
fi

command -v nmap >/dev/null 2>&1 || { echo >&2 "nmap is required but not installed. Aborting."; exit 1; }
command -v awk >/dev/null 2>&1 || { echo >&2 "awk is required but not installed. Aborting."; exit 1; }

#[[ $UID -ne 0 ]] && { echo "this script requires root privileges" >&2; exit 1; }

#nmap -sP ${subnet} | grep -i ${macstr} -B2 | grep "Nmap scan report for" | awk 'BEGIN {FS="for"} {print $2}' | tr -d ' ()'

# add - use sudo to run it here, otherwise using sudo in command line to run this script, it will fail when this script is put to ~/bin/
# add - remove leading whitespace
# add - filter string because nmap sometimes output like
#       xxx.xxx.xxx.xxx (192.168.1.234) or (192.168.1.234)
#       so we just extract value from ( )
sudo nmap -sP ${subnet} | grep -i ${macstr} -B2 | grep "Nmap scan report for" | awk 'BEGIN {FS="for"} {print $2}' | sed 's/^[ \t]*//' | grep -Po '\(\K[^)]+(?=\))'
