#!/bin/bash
# -t : Display TCP sockets/port
# -u : Show UDP sockets/port
# -l : See only listening sockets i.e. open port
# -p : Also display process name that opened port/socket
# -n : View addresses and port numbers in numerical format. Do not use DNS to resolve names.
sudo ss -tulpn
