#!/bin/bash
# refer to https://github.com/aviaryan/utility-bash-scripts/blob/master/youtube-video
function failed()
{
    echo "$*" >&2
    exit 1
}

if [ "$1" ]; then
    url=$1
else
    failed "url is needed"  
fi

if [ ! -d ~/Downloads/Videos ]; then
    mkdir -p ~/Downloads/Videos
fi

cd ~/Downloads/Videos || return

format=mp4

# download
if hash aria2c 2> /dev/null; then
    youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' --merge-output-format ${format} --external-downloader aria2c -o '%(title)s-%(id)s-%(format_id)s.%(ext)s' "$url"
else
    youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' --merge-output-format ${format} -o '%(title)s-%(id)s-%(format_id)s.%(ext)s' "$url"
fi
